stages:
  - lint

flake8:lint:
  stage: lint
  image: python:3.11-slim
  before_script:
    - python -m pip install --upgrade pip
    - pip install flake8
  script:
    - flake8 --max-line-length=120 --extend-exclude .venv,venv,.pytest_cache,.playwright-mcp --statistics --count src tests modules
