stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTEST_ADDOPTS: "-q --junitxml=report.xml"

cache:
  paths:
    - .cache/pip

pytest:
  stage: test
  image: python:3.11-slim
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest
  artifacts:
    when: always
    reports:
      junit: report.xml
    paths:
      - report.xml
